package main

import (
	"fmt"
	"math/rand"
	"net/http"
	"path/filepath"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
)

type Pong struct {
	Pong bool      `json:"pong" example:"true"`
	Time time.Time `json:"time" example: "2023-08-27T09:00:00`
}

func NewAppServer() *echo.Echo {
	e, unsecured := InitAppServer("v1")

	// basic ping handler
	unsecured.GET("ping", PingHandler)

	unsecured.GET("scale", Scale)
	unsecured.GET("entities", GetEntities)
	unsecured.GET("entity/:eid", GetOneEntity)

	unsecured.POST("input", CreateEntryHandler)
	unsecured.GET("input", GetEntries)
	unsecured.DELETE("input/:rid", DeleteEntry)

	return e
}

func PingHandler(c echo.Context) error {
	return c.JSON(http.StatusOK, time.Now())
}

func Scale(c echo.Context) error {

	weigth := rand.Float32()
	stable := rand.Int31n(10) > 3
	if !stable {
		weigth *= 0.3 + rand.Float32()
	}

	data := map[string]interface{}{
		"value":  weigth,
		"stable": true,
	}
	// jsonData, err := json.Marshal(data)
	return c.JSON(http.StatusOK, data)
}

func InitAppServer(version string) (*echo.Echo, *echo.Group) {
	e := echo.New()
	e.Use(middleware.CORS())
	e.HideBanner = true

	// e.Use(middleware.Logger())

	notSecured := e.Group(fmt.Sprintf("api/%s/", version))

	e.GET("swagger/*", echoSwagger.WrapHandler)

	static := e.Group("static")
	static.Use(middleware.Static(filepath.Join("static")))
	e.File("/", "index.html")

	// e.Logger.SetLevel(loglv1.WARN)
	// e.Use(acecho.LogException())
	return e, notSecured
}

func main() {
	session := GetDbSession()
	LoadConfiguration("configuration.xlsx")

	if session == nil {
		panic("Failed connect to database")
	}

	e := NewAppServer()

	e.Logger.Fatal(e.Start(":5000"))
}
